<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ClipRef</RootNamespace>
    <AssemblyName>ClipRef</AssemblyName>
    <ApplicationIcon>Assets\ClipRef.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\ClipRef.ico">
      <LogicalName>ClipRef.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\success.ico">
      <LogicalName>ClipRef.success.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\warning.ico">
      <LogicalName>ClipRef.warning.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\failure.ico">
      <LogicalName>ClipRef.failure.ico</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
